packages:
  - packages/*
  - apps/*
  - examples/*

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

packageExtensions:
  "@analogjs/vite-plugin-angular":
    peerDependencies:
      typescript: ">=5.4.0 <5.9.0"
